### PR TITLE
Track all individual minor versions of Safari 15+

### PR DESCRIPTION
**Pull request by queengooborg**
This PR updates the ua-parser script to track all Safari 15+ minor versions as individual releases, rather than mapping down (as needed for Samsung Internet and older Safari releases).

### CODE REVIEW

**Review by foolip — COMMENTED** [review]
Can you add some tests for this? I'd expect the current code to work if BCD has the individual 15.x releases, but that there will be a problem with 15.6 if only 15.5 is in BCD currently. But this problem isn't explicitly handled here...

Ultimately, which cases will this change?

**Comment by foolip** [comment]
Thinking about this some more, I don't think there was actually a change with regards to minor versions at 15+, only the pace. Both before at after, the minor version is often significant for Safari, but we might have minor versions that we'll skip in BCD if there were no web exposed changes.

So some examples would help.

**Comment by queengooborg** [comment]
> I don't think there was actually a change with regards to minor versions at 15+, only the pace

I meant to say "Safari iOS", since there would be a few minor releases of iOS in between Safari minor releases.  For Safari Desktop, every minor version is just as important as every major version, especially with the more frequent updates now!

**Comment by foolip** [comment]
https://github.com/foolip/mdn-bcd-collector/pull/2208 is more like what I'd prefer here. 15+ aren't special, right?

**Pull request merged**
