### PR TITLE
Updates color contrast ratios to ensure they are meeting WCAG 2.0 AA

### LINKED ISSUE #1410: Accessibility concerns on mdn-bcd-collector website
After running a [Lighthouse](https://developers.google.com/web/tools/lighthouse) audit on https://mdn-bcd-collector.appspot.com/, we receive this audit report:

CC @vinyldarkscratch 

Screen Shot 2021-08-17 at 3 46 39 PM

The Performance and and Best Practices scores are great (performance could be improved), but the Accessibility and SEO definitely need some work. Contrast ratios failing WCAG 2.0 and images with alt text, along with a few other things. They are all quick fixes so I will pepper a single PR with the majority of the changes.

## Accessibility report
Issues needing to be fixed:
- Background and foreground colors do not have a sufficient contrast ratio.
- Image elements do not have [alt] attributes
- `<html>` element does not have a [lang] attribute
Screen Shot 2021-08-17 at 4 01 31 PM

## SEO report
Issues needing to be fixed:
- Document does not have a meta description
- Image elements do not have [alt] attributes

Screen Shot 2021-08-17 at 4 01 51 PM

### PR DESCRIPTION
**Pull request by tannerdolby**
Fixes #1410 

This should resolve the remaining issues from the Lighthouse audit. I think everything looks good now that we are WCAG AA compliant for color contrast. Feel free to pull into this branch and have a look or view the short demo below.

Updated colors:
- button, select, input - Bg: `#3D853F` / Foreground: `#FFF` - Ratio: 4.54: 1
- button:hover, select:hover, input[type=submit]:hover - Bg: `#0F8A13` / Foreground: `#FFF` - Ratio: 4.5:1
- input::placeholder - Bg: `#FEFEFE` / Foreground: `#3D853F` - Ratio: 4.5:1

https://user-images.githubusercontent.com/48612525/130120045-324286f4-605f-48e4-8bfc-7ceca9801a86.mov

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Thanks for tackling this!  I just have a few comments so far:

Are you planning to update the dark theme colors as well, or are they already good to go?

Can we ensure that the contrast between regular and hovering states remain higher?  With these changes, the contrast between them is significantly lower (I barely noticed it in the recorded video), and while that's not explicitly an accessibility guideline, I feel it's important to keep.  I think keeping the hover state a lighter color is important, so let's bring the regular color down?

**Comment by tannerdolby** [comment]
> Are you planning to update the dark theme colors as well, or are they already good to go?

Your welcome! With this PR there are no longer any contrast ratio issues on the page so I wasn't planning to change anything else.

> Can we ensure that the contrast between regular and hovering states remain higher? With these changes, the contrast between them is significantly lower (I barely noticed it in the recorded video), and while that's not explicitly an accessibility guideline, I feel it's important to keep.

Yeah this is where I wanted to discuss tradeoffs with you. The proposed changes do satisfy 4.5:1 for initial and hover states in the form, but with the darker initial background transitioning to a lighter hover state background, it is quite tough to notice a difference between states.

So I agree, with the contrast ratios now over 4.5:1 and this shade of green, its hard to find a "brighter" hover state to really differentiate between the initial darker state and lighter hover state. I do think its noticeable (the change between backgrounds) when hovering the `input`'s but it could be improved for a better user experience.

>  I think keeping the hover state a lighter color is important, so let's bring the regular color down?

Ok deal, I think that sounds like a plan. When you say "bring the regular color down" are you referring to making initial background color lighter or darker?

**Comment by tannerdolby** [comment]
I made the initial state background-color a bit darker from `#3D853F` to `#2F6F31` and that has a 6.1:1 ratio which is superb. The contrast is now quite a bit higher between the initial and hover state backgrounds so its easier to tell whether your hovered over the element or not.

Demo video, or just pull into this branch and have a look:

https://user-images.githubusercontent.com/48612525/132752159-3990af9c-2eb8-4b00-b7da-5eb83a999446.mov

**Comment by queengooborg** [comment]
I recently converted our CSS to SCSS to allow for easier color changes.  Would you like to rebase this PR to accommodate for this change?

**Comment by tannerdolby** [comment]
Yeah, sure thing!

**Pull request closed without merging**
